### ISSUE TITLE
Support for VSCodium

### ISSUE THREAD

**Issue by xRealNeon** [plibither8/ulauncher-vscode-recent#10]
Hey, I am using [VSCodium](https://vscodium.com/), and it won't work. Can you add support for it?

![grafik](https://user-images.githubusercontent.com/20997346/138475742-2e4dd394-c27a-4610-afb4-7e3bfc860fc3.png)

**Comment by mattalexx** [comment]
Fixed by PR #6

**Comment by mattalexx** [comment]
Vote to close?

**Comment by mattalexx** [comment]
@plibither8

**Comment by plibither8** [comment]
Whoops, missed this. Sure!

By the way @mattalexx, I sent you an email a couple days ago regarding, would love it if you could go over it :smile:!
