### ISSUE TITLE
crashes due to not being able to import fuzzywuzzy

### ISSUE THREAD

**Issue by Luramoth** [plibither8/ulauncher-vscode-recent#11]
I used pip to install the library but it didn't work after refreshing and re opening Ulauncher, not quite sure what could be the problem

**Comment by michaelGRU** [comment]
Are you using a conda environment? If so, try pip install fuzzywuzzy when conda is activated. Then sudo reboot.

**Comment by mattalexx** [comment]
@Luramoth Is this still a problem for you?

**Comment by Luramoth** [comment]
> @Luramoth Is this still a problem for you?

No but that's because I distro hopped to pop os and I don't even need ulauncher lol
