### ISSUE TITLE
To open  vs code project folders, When i write code & space it is not showing me folders.

### ISSUE THREAD

**Issue by gnande** [plibither8/ulauncher-vscode-recent#12]
To open  vs code project folders, When i write code & space it is not showing me folders.
It is suddenly crashed.

![vsccode error](https://user-images.githubusercontent.com/62431058/152630867-6d7b4ca2-1cb4-41ac-a63d-0a8b218c5446.JPG)

![vsccode error1](https://user-images.githubusercontent.com/62431058/152630878-fe643fec-aa98-4d73-845a-5b13d61f28c6.JPG)

**Comment by gnande** [comment]
@mattalexx Could you please help on above issue ?

**Comment by mattalexx** [comment]
I would need to see the logs. Stop the ulauncher service and run `ulauncher -v` in a terminal. Then try to get the error to show up. Then paste that here.

**Comment by gnande** [comment]
[ulog.txt](https://github.com/plibither8/ulauncher-vscode-recent/files/8007596/ulog.txt)

**Comment by mattalexx** [comment]
Hm, that's still not enough for me to go on. Could you run the command again, but this time add `--dev`?

```
ulauncher -v --dev
```

cc @plibither8 <-Creator/maintainer

**Comment by gnande** [comment]
[ulauncherlog.txt](https://github.com/plibither8/ulauncher-vscode-recent/files/8007815/ulauncherlog.txt)

@mattalexx Please check the new log file ulauncherlog.txt

**Comment by mattalexx** [comment]
Sorry, I'm not sure what "WS Client error" means. Haven't seen that before.

**Comment by gnande** [comment]
I am getting this error only on vs code. If I do "fd <any directory>" Or "ff <any file>" then it is working fine.
But for vs code, if I do "code " it is not populating project folder list.  Initially it was working but then for vs code it is crashing now.
@mattalexx  @plibither8

**Comment by plibither8** [comment]
Hmm interesting. Can't make out much from the logs. Could you share your recent projects file? You'll probably find it in `~/.config/Code/storage.json`.

**Comment by gnande** [comment]
[vscode.txt](https://github.com/plibither8/ulauncher-vscode-recent/files/8008074/vscode.txt)

Please find attached file. @plibither8

**Comment by mattalexx** [comment]
@gnande One thing you might try is to revert PR #6. You will lose support for workspaces and also for VSCodium, but you might see the problem disappear.

That would look something like this if you're on Linux:

```shell
cd ~/.local/share/ulauncher/extensions
mv com.github.plibither8.ulauncher-vscode-recent com.github.plibither8.ulauncher-vscode-recent_bak
git clone git@github.com:plibither8/ulauncher-vscode-recent.git com.github.plibither8.ulauncher-vscode-recent
cd com.github.plibither8.ulauncher-vscode-recent
git reset --hard 4abe46f8975434c9a4d0aac5e3cfc2ceb4e035fb
```

I haven't tested this, I'm just trying to remember how the steps went. But these are the docs I followed:

https://docs.ulauncher.io/en/latest/extensions/intro.html

**Comment by xddxdd** [comment]
Hi, I also encountered this error, after updating VS Code (official binary version) from 1.63.2 to 1.64.0.

The relevant error in `ulauncher -v --dev` is:

```
om.github.plibither8.ulauncher-vscode-recent | 2022-02-06 00:34:04,651 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3.10/site-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/lantian/.local/share/ulauncher/extensions/com.github.plibither8.ulauncher-vscode-recent/main.py", line 125, in on_event
    items.extend(extension.get_ext_result_items(argument))
  File "/home/lantian/.local/share/ulauncher/extensions/com.github.plibither8.ulauncher-vscode-recent/main.py", line 82, in get_ext_result_items
    recents = self.code.get_recents()
  File "/home/lantian/.local/share/ulauncher/extensions/com.github.plibither8.ulauncher-vscode-recent/main.py", line 46, in get_recents
    openedPaths = storage["openedPathsList"]["entries"]
KeyError: 'openedPathsList'
```

**Comment by mattalexx** [comment]
I just updated VSCodium and I'm also seeing the problem. Give me a bit and I'll see what I can do to fix it.
