### ISSUE TITLE
The VsCode 1.64 isn't solved with the latest update 

### ISSUE THREAD

**Issue by gabey14** [plibither8/ulauncher-vscode-recent#15]
Got this

Traceback (most recent call last):
  File "/home/abey/.local/share/ulauncher/extensions/com.github.plibither8.ulauncher-vscode-recent/main.py", line 33, in <module>
    class Code:
  File "/home/abey/.local/share/ulauncher/extensions/com.github.plibither8.ulauncher-vscode-recent/main.py", line 79, in Code
    def get_recents_global_state(self) -> list[dict[str, str]]:
TypeError: 'type' object is not subscriptable

**Comment by mattalexx** [comment]
I was unable to exactly recreate that error but I removed the type hinting that seems to be causing it. Let me know if it's fixed now.

**Comment by WandersonAlves** [comment]
I have updated and got this:
![image](https://user-images.githubusercontent.com/9141449/153259139-a9d6bb09-fe40-4b2e-8cb6-ed716e902f31.png)
I don't know how to get the logs :(

**Comment by gabey14** [comment]
> I have updated and got this: ![image](https://user-images.githubusercontent.com/9141449/153259139-a9d6bb09-fe40-4b2e-8cb6-ed716e902f31.png) I don't know how to get the logs :(

I think u should stop it and start it again

**Comment by gabey14** [comment]
> I was unable to exactly recreate that error but I removed the type hinting that seems to be causing it. Let me know if it's fixed now.

Yea so I made a pr please check it out.

**Comment by WandersonAlves** [comment]
Fixed! Thanks

**Comment by gabey14** [comment]
> Thanks for the assist @gabey14 

Personally I use this daily and it helps and saves me alot of time so thank u for this. My pleasure helping out and also made my first pull request and open source contribution through this 😄.Thank you.
