### ISSUE TITLE
"no VSCode?" even though I have vscode installed

### ISSUE THREAD

**Issue by NishantDesai1306** [plibither8/ulauncher-vscode-recent#18]
I installed this extension but even though I have VSCode installed (and `code` command active in terminal) the extension just says that "can't find vscode's code command in system"

![image](https://user-images.githubusercontent.com/18420157/167279051-6398349f-d4c1-4148-949f-6d3f38f16e6c.png)

![image](https://user-images.githubusercontent.com/18420157/167279063-50d10f98-d66e-4447-8e13-f3cd9bda8bc3.png)

**Comment by gabey14** [comment]
How did you install VsCode?

**Comment by NishantDesai1306** [comment]
yeah, that's what I'm showing in second secreenshot that, I have VSCode installed and the `code` is present in PATH

**Comment by gianmaria89** [comment]
same problem from today

**Comment by cesar32az** [comment]
Same problem.
- vscode 1.67

**Comment by gabey14** [comment]
I have fixed the error please merge it to the main branch @mattalexx @plibither8

**Comment by SIMULATAN** [comment]
If you want to use the fixed version from @gabey14, I forked his repo and renamed the branch to "main" to make it installable. You can find the fixed version [here](https://github.com/SIMULATAN/ulauncher-vscode-recent)

**Comment by plibither8** [comment]
Thanks for the patience everyone! I've merged the PR, fixed in #19.
