### ISSUE TITLE
[FEATURE] Fuzzy Search

### ISSUE THREAD

**Issue by WandersonAlves** [plibither8/ulauncher-vscode-recent#2]
Hi, first of all, thanks for the extension.

Can a fuzzy search be implemented? I wanna type `code monorepo` and list all recent vscode with the `monorepo` keyword.

Thanks!

**Comment by plibither8** [comment]
Good point! I'll see if I get time thos weekend to hack it up :)

**Comment by plibither8** [comment]
@WandersonAlves It's live now :)

Note: You will have to install the `fuzzywuzzy` module: `pip install fuzzywuzzy`
