### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by gabey14** [plibither8/ulauncher-vscode-recent#3]

**Comment by plibither8** [comment]
Umm... could you provide any more details? "Crashed" doesn't really help. Thanks

**Comment by gabey14** [comment]
So the VsCode Recent extension crashed

[image: image.png]
Getting this Error when i ran it in verbose mode Hope this helps

com.github.plibither8.ulauncher-vscode-recent | 2021-09-27 22:50:42,528 |
DEBUG | ulauncher.api.client.Client: on_message() | Incoming event
PreferencesEvent
com.github.plibither8.ulauncher-vscode-recent | 2021-09-27 22:51:07,403 |
DEBUG | ulauncher.api.client.Client: on_message() | Incoming event
KeywordQueryEvent
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py",
line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py",
line 52, in trigger_event
    action = listener.on_event(event, self)
  File
"/home/abey/.local/share/ulauncher/extensions/com.github.plibither8.ulauncher-vscode-recent/main.py",
line 125, in on_event
    items.extend(extension.get_ext_result_items(argument))
  File
"/home/abey/.local/share/ulauncher/extensions/com.github.plibither8.ulauncher-vscode-recent/main.py",
line 82, in get_ext_result_items
    recents = self.code.get_recents()
  File
"/home/abey/.local/share/ulauncher/extensions/com.github.plibither8.ulauncher-vscode-recent/main.py",
line 49, in get_recents
    uri = path["folderUri"] if folder else path["fileUri"]
KeyError: 'fileUri'

**Comment by gabey14** [comment]
Could u tell me why I really use this extension everyday and in love with it. Would love to get it resolved ASAP. Thanks for this beautiful extension and would love to help 😊

**Comment by gabey14** [comment]
@plibither8 Any Solution?Thank you

**Comment by gabey14** [comment]
Bro got it resolved actually in the storage.json file there was a workspace entry which was deleted but was still showing in the storage.json file hence it was giving an error I hope u could make a fix to handle such an error.
