### ISSUE TITLE
Using Workspaces breaks the extension

### ISSUE THREAD

**Issue by hakonmh** [plibither8/ulauncher-vscode-recent#8]
The extension breaks if one of the recently opened items is a workspace file.

I've done some testing and the python file throws the following exception:
`File "/home/hakonmh/Programming/Temp/vscode-recent.py", line 24, in get_recents`
`uri = path["folderUri"] if folder else path["fileUri"]`
`KeyError: 'fileUri'`

The signature of `path`:
`{'workspace': {'id': 'aaf5d6b49aad427cc7fced16975287cb', 'configPath': 'file:///home/hakonmh/Programming/Temp/test.code-workspace'}}`

**Comment by mattalexx** [comment]
Fixed by PR #6
